name: tic_tac_toe
description: Play offline, with friends, or online worldwide. Customize boards & themes.

version: 1.0.2+3

environment:
  sdk: '>=3.1.0-149.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_database: ^10.2.2
  firebase_core: ^2.13.1
  audioplayers: ^4.1.0
  google_fonts: ^5.1.0
  provider: ^6.0.5
  widget_and_text_animator:
    git:
      url: https://github.com/princesanjivy/widget_and_text_animator.git
      ref: main
  vibration: ^1.8.1
  shared_preferences: ^2.1.2
  page_transition: ^2.0.9
  share_plus: ^7.0.2
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4
  fluttertoast: ^8.0.8
  cloud_firestore: ^4.8.2
  flutter_svg: ^2.0.7
  clipboard: ^0.1.3
  url_launcher: ^6.1.14
  google_mobile_ads: ^3.0.0

dependency_overrides:
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/audio/
    - assets/images/

